// 22 張大阿爾克那（Major Arcana）
// 每張牌包含：編號、中英名、羅馬數字、核心關鍵字、正位/逆位解讀、中央符號 (SVG-friendly glyph)
const ARCANA = [
  { num: 0,  roman: "0",     name: "愚者",       en: "The Fool",            keyword: "純真．冒險．新旅程",
    upright: "聽從直覺，踏出第一步。未知的旅途正在等待你。",
    reversed: "魯莽、猶豫不決，或對風險缺乏準備。",
    glyph: "☼" },
  { num: 1,  roman: "I",     name: "魔術師",     en: "The Magician",        keyword: "意志．創造．行動",
    upright: "你擁有所需的一切資源，將想法化為現實的時機已到。",
    reversed: "才能被誤用、口是心非，或被自身的能力所迷惑。",
    glyph: "∞" },
  { num: 2,  roman: "II",    name: "女祭司",     en: "High Priestess",      keyword: "直覺．潛意識．奧秘",
    upright: "靜默聆聽內在的聲音，答案藏於沉思之中。",
    reversed: "忽略直覺、訊息被遮蔽，內外失衡。",
    glyph: "☾" },
  { num: 3,  roman: "III",   name: "皇后",       en: "The Empress",         keyword: "豐盛．孕育．感官",
    upright: "創造力與生命力充盈，是收穫與愛的時節。",
    reversed: "依賴、過度給予，或創造力受阻。",
    glyph: "♀" },
  { num: 4,  roman: "IV",    name: "皇帝",       en: "The Emperor",         keyword: "秩序．權威．結構",
    upright: "建立穩固的根基，以理性與紀律掌握全局。",
    reversed: "專制、僵化，或失去主導權。",
    glyph: "♂" },
  { num: 5,  roman: "V",     name: "教皇",       en: "The Hierophant",      keyword: "傳統．信念．指引",
    upright: "遵循既定的智慧傳統，導師或制度將給予幫助。",
    reversed: "挑戰權威、打破傳統，走自己的道路。",
    glyph: "✠" },
  { num: 6,  roman: "VI",    name: "戀人",       en: "The Lovers",          keyword: "選擇．連結．和諧",
    upright: "重要的選擇與深刻的連結，請忠於內心。",
    reversed: "失衡的關係、誤解、價值觀衝突。",
    glyph: "✧" },
  { num: 7,  roman: "VII",   name: "戰車",       en: "The Chariot",         keyword: "意志．前進．掌控",
    upright: "以堅定意志駕馭對立的力量，邁向勝利。",
    reversed: "失控、目標模糊，或對抗中內耗。",
    glyph: "⛛" },
  { num: 8,  roman: "VIII",  name: "力量",       en: "Strength",            keyword: "勇氣．柔韌．馴服",
    upright: "以溫柔的堅毅面對挑戰，內在的力量勝過蠻力。",
    reversed: "自我懷疑、情緒失控，或被恐懼支配。",
    glyph: "∞" },
  { num: 9,  roman: "IX",    name: "隱者",       en: "The Hermit",          keyword: "沉思．孤獨．啟示",
    upright: "退一步，獨自走向內在，光會從心中升起。",
    reversed: "孤立、迷失方向，或拒絕被理解。",
    glyph: "✦" },
  { num: 10, roman: "X",     name: "命運之輪",   en: "Wheel of Fortune",    keyword: "轉變．循環．時機",
    upright: "命運之輪轉動，新的循環即將到來。",
    reversed: "抗拒改變、運勢受阻，或停留於舊習慣。",
    glyph: "☯" },
  { num: 11, roman: "XI",    name: "正義",       en: "Justice",             keyword: "公平．因果．真相",
    upright: "事情會以應有的方式平衡，誠實與責任是關鍵。",
    reversed: "偏見、逃避責任，或不公的結果。",
    glyph: "⚖" },
  { num: 12, roman: "XII",   name: "倒吊人",     en: "The Hanged Man",      keyword: "暫停．犧牲．新視角",
    upright: "暫停，換一個角度看，犧牲將帶來新的領悟。",
    reversed: "停滯、無謂的犧牲，或拒絕轉換觀點。",
    glyph: "⟂" },
  { num: 13, roman: "XIII",  name: "死神",       en: "Death",               keyword: "終結．蛻變．重生",
    upright: "一段循環結束，新生命從蛻變中誕生。",
    reversed: "抗拒結束、停留過去，或變化來得遲緩。",
    glyph: "✕" },
  { num: 14, roman: "XIV",   name: "節制",       en: "Temperance",          keyword: "平衡．調和．整合",
    upright: "耐心調和對立的元素，找到中道。",
    reversed: "過度、失衡，或急於求成。",
    glyph: "△" },
  { num: 15, roman: "XV",    name: "惡魔",       en: "The Devil",           keyword: "束縛．執念．陰影",
    upright: "看清困住你的執念，鎖鏈其實在自己手中。",
    reversed: "從束縛中解脫，重新奪回主導權。",
    glyph: "⛧" },
  { num: 16, roman: "XVI",   name: "高塔",       en: "The Tower",           keyword: "崩塌．覺醒．真相",
    upright: "舊有結構崩塌，真相以閃電之姿降臨。",
    reversed: "延遲的崩塌、勉強維持，或內在的危機。",
    glyph: "▲" },
  { num: 17, roman: "XVII",  name: "星星",       en: "The Star",            keyword: "希望．療癒．指引",
    upright: "風暴之後的寧靜，希望之光重新照亮前路。",
    reversed: "失去信心、希望黯淡，或自我懷疑。",
    glyph: "✧" },
  { num: 18, roman: "XVIII", name: "月亮",       en: "The Moon",            keyword: "幻象．潛意識．迷霧",
    upright: "穿越迷霧，傾聽夢境與直覺的訊息。",
    reversed: "迷霧散去，真相浮現；或仍被恐懼蒙蔽。",
    glyph: "☽" },
  { num: 19, roman: "XIX",   name: "太陽",       en: "The Sun",             keyword: "光明．喜悅．成就",
    upright: "光與生命綻放，純粹的喜悅與成功降臨。",
    reversed: "光芒被遮蔽、過度樂觀，或喜悅延遲。",
    glyph: "☀" },
  { num: 20, roman: "XX",    name: "審判",       en: "Judgement",           keyword: "覺醒．召喚．清算",
    upright: "聽見內在的召喚，是時候做出最終的決定。",
    reversed: "自我批判、忽略召喚，或無法原諒自己。",
    glyph: "♁" },
  { num: 21, roman: "XXI",   name: "世界",       en: "The World",           keyword: "完成．圓滿．整合",
    upright: "一段旅程圓滿結束，你已完整地成為自己。",
    reversed: "未完成、缺口仍在，或無法放下舊章節。",
    glyph: "✺" },
];

// 牌陣定義：每個位置有 label（用途）、x/y（百分比定位）、rot（旋轉角度）
const SPREADS = {
  single: {
    id: "single",
    name: "單張牌陣",
    sub: "Single Card",
    desc: "對一個明確的問題給予直接的答覆。最簡潔，也最深刻。",
    count: 1,
    positions: [
      { label: "核心訊息", x: 50, y: 50 },
    ],
  },
  trinity: {
    id: "trinity",
    name: "聖三角牌陣",
    sub: "Holy Trinity",
    desc: "經典的三張牌陣，從時間或情境的三個面向揭示全貌。",
    count: 3,
    positions: [
      { label: "過去 · 因",    x: 22, y: 50 },
      { label: "現在 · 此刻",  x: 50, y: 50 },
      { label: "未來 · 果",    x: 78, y: 50 },
    ],
  },
  core: {
    id: "core",
    name: "直指核心",
    sub: "The Core",
    desc: "四張牌深入剖析現況、阻礙、建議與結果。",
    count: 4,
    positions: [
      { label: "現況",         x: 18, y: 50 },
      { label: "阻礙",         x: 40, y: 50 },
      { label: "建議",         x: 62, y: 50 },
      { label: "結果",         x: 84, y: 50 },
    ],
  },
  celtic: {
    id: "celtic",
    name: "凱爾特十字",
    sub: "Celtic Cross",
    desc: "塔羅最經典的十張牌陣，全方位解讀人生課題的每個面向。",
    count: 10,
    positions: [
      { label: "1. 現況",        x: 26, y: 50 },
      { label: "2. 挑戰",        x: 26, y: 50, rot: 90, overlay: true },
      { label: "3. 根基",        x: 26, y: 82 },
      { label: "4. 過去",        x: 10, y: 50 },
      { label: "5. 目標",        x: 26, y: 18 },
      { label: "6. 不久將來",    x: 42, y: 50 },
      { label: "7. 自我態度",    x: 70, y: 82 },
      { label: "8. 外在影響",    x: 70, y: 60 },
      { label: "9. 希望與恐懼",  x: 70, y: 38 },
      { label: "10. 最終結果",   x: 70, y: 16 },
    ],
  },
};

window.ARCANA = ARCANA;
window.SPREADS = SPREADS;
